решение 04-Layouts (04-SPA)
js-tasks-ru/vue-20200925-2_ann2 pull request #10
Opened 2020-10-21 20:35 UTC by Akaciya

2020-10-21 20:57 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Layouts
+ TheHeader не долж��н быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-23 14:46 UTC, ShGKme requested changes
Плохо понял, что именно вы пытались реализовать...

Требуется в BaseLayout добавить вёрстку, общую для всех страниц проекта.
В AuthLayout - общую только для страниц входа и регистрации (https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/login.html).
В FormLayout - общую только для страниц с формами (https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/meetup-form.html)

2020-10-23 14:46 UTC, ShGKme commented on 04-SPA/04-Layouts/components/TheHeader.vue
> +            </svg>
Изображение лучше вставить как `<img src="/img/logo" />`. Если оно будет маленьким, webpack сам заменит его на inline изображение, а стилизовать SVG здесь не требуется.

2020-10-23 14:46 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
> +  .page.page_meetup-forms {
Кажется, этот класс нигде не используется...

Шаблон должен иметь разметку:
```html
<div class="page page_meetup-forms">
            <div class="container">
```

https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/meetup-form.html

2020-10-23 14:46 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +  </div>
Не хватает вёрстки страниц авторизации: https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/login.html

2020-10-23 14:46 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +    this.$emit(`update: layout`, BaseLayout);
Нужна ли эта синхронизация?
Нужен ли вообще текущий компонент, если в итоге будет выводиться `BaseLayout`?

2020-10-23 15:00 UTC, Akaciya commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +    this.$emit(`update: layout`, BaseLayout);
У задачи была указана ссылка 
на подходы https://markus.oberlehner.net/blog/dynamic-vue-layout-components/
сделала как там, по образцу
В задании также указана картинка 
https://i.imgur.com/8dOjt5J.png, 
которая в итоге должна получиться, 
как я поняла.

2020-10-23 15:03 UTC, Akaciya commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +    this.$emit(`update: layout`, BaseLayout);
К чему был указан в задании
универсальный компонент, 
если его не нужно было использовать?

2020-10-23 15:21 UTC, Akaciya commented on 04-SPA/04-Layouts/components/FormLayout.vue
> +  .page.page_meetup-forms {
Верстку брала с боевого сайта, т.к. на 
тот момент не знала о ссылке https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/meetup-form.html
Она указана в следующем задании.

2020-10-25 14:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-25 14:52 UTC, Akaciya commented
добавлено 2 задачки: 04-Layouts, 05-AuthPages

2020-10-25 15:17 UTC, ShGKme requested changes
По задаче Layouts требуется ещё небольшое исправление.

Задача `AuthPages` принята.

2020-10-25 15:17 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +    <div class="page page_meetup-forms">
`page_meetup-forms` - на страницах с формами митапа (создание, редактирование).

https://github.com/js-tasks-ru/vue-20200925-course-materials/blob/master/meetups-design-layout/login.html#L30

2020-10-25 17:16 UTC, Akaciya commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +    <div class="page page_meetup-forms">
да, чет напутала, поправлю

2020-10-25 17:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-25 18:22 UTC, ShGKme approved these changes
Принято 👍

2020-10-25 18:23 UTC, merged