решение задачи 04-DropdownButton-1
js-tasks-ru/vue-20200925-2_ann2 pull request #7
Opened 2020-10-13 18:31 UTC by Akaciya

уборка в предыдущих компонентах AppToast, FormGroup

2020-10-13 18:41 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 03-vue-cli/04-DropdownButton-1/__tests__/DropdownButton-1.test.js — добавлен
```

2020-10-13 18:50 UTC, Akaciya commented
в смысле добавлен? он там и был

2020-10-13 20:43 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 03-vue-cli/04-DropdownButton-1/__tests__/DropdownButton-1.test.js — добавлен
```

2020-10-13 20:57 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 03-vue-cli/04-DropdownButton-1/__tests__/DropdownButton-1.test.js — добавлен
```

2020-10-14 08:31 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
DropdownButton-1
+ Компонент должен иметь параметры title, options, value
+ Кнопка должна иметь текст с заголовком из параметра
+ Кнопка должна иметь текст с заголовком и выбранным вариантом
+ Компонент должен реагировать на изменение выбранного варианта
+ Компонент должен показывать список скрытым, открывать его по клику и закрывать по повторному клику
+ Выбор вариант порождает событие change
+ Список должен скрываться после выбора варианта
+ Должен быть класс dropdown__toggle_icon и иконка на кнопке выбранного варианта при наличии icon в списке вариантов
+ Должен быть класс dropdown__item_icon на все вариантах, если хотя бы у одного есть иконка
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-14 08:34 UTC, ShGKme requested changes
В DropdownButton требуется избавиться от вызова метода в шаблоне...

2020-10-14 08:34 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +  <div class="dropdown" :class="{ show: this.show }" @click="toggleShow">
В шаблоне не нужно писать `this`.

2020-10-14 08:34 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +      :class="{ dropdown__toggle_icon: checkIcon() }"
Вызывать методы в шаблоне - плохая практика.
Здесь должно быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут вызываться только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кешируется.

2020-10-14 08:34 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +    },
Это - явно вычисляемое свойство, а не метод. `checkIcon` можно вычислить из значения `this.options` и пересчитывать, когда оно меняется.

2020-10-14 13:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-14 14:33 UTC, ShGKme approved these changes
Принято 👍

2020-10-14 14:33 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +    setAction: function () {
Не очень удачное название для свойства. Глагол, действие, метод

2020-10-14 14:34 UTC, merged

2020-10-14 14:38 UTC, Akaciya commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +    setAction: function () {
согласна. Учту.
Изначально придумывала 
под одно. Потом переделывала, 
а название осталось